package main

// Command refs-rehash refreshes the per-item "outputs" SHA1 maps in
// _refs.json files from the artifact files on disk.
//
// After regenerating fixture outputs (layout-test-runner rewrites
// *.layout.json, ipmsvg-gen rewrites *.ipm.svg, gen-test-md rewrites *.md),
// the "outputs" hashes recorded in _refs.json are stale. A full
// `sync-test-cases` run re-walks every source glob to rebuild them; this tool
// does just the hash refresh, in place, without re-extracting anything.
//
// Only the "outputs" maps are touched: source_sha1 / content_sha1 keep
// tracking the documentation source, so doc drift is still detected by
// `sync-test-cases --check`. For each item the candidate output set is the
// union of the keys already recorded and the standard generated suffixes
// (json, layout.json, ipm.svg, md); a key is dropped when its file no longer
// exists, mirroring sync-test-cases' buildRefs.
//
// Usage:
//
//	go run ./cmd-dev/refs-rehash [--check] [-v] [dir ...]
//
// Each dir must contain a _refs.json. With no args the three layout corpora
// (tests/layout-gen, tests/layout-gen-ext, tests/layout-gen-shells) are
// refreshed. Exit 0 when everything is fresh or was refreshed, 1 when --check
// found stale hashes, 2 on read/write errors.
//
// Related: gl:cmd-dev/sync-test-cases/main.go gl:pkg/filterutil/filterutil.go

import (
	"crypto/sha1"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/infinite-pm/ipm-tools/pkg/cli"
	"github.com/infinite-pm/ipm-tools/pkg/filterutil"
)

// defaultDirs are the corpora whose outputs are routinely regenerated by the
// layout-engine workflow (layout-test-runner + ipmsvg-gen + gen-test-md).
var defaultDirs = []string{
	"tests/layout-gen",
	"tests/layout-gen-ext",
	"tests/layout-gen-shells",
}

// standardOutputKeys are the generated-artifact suffixes sync-test-cases
// records besides the snippet's own extension key (ipmt, ipmt-invalid, ...).
// "ipmt" is included because sync-test-cases does NOT record the snippet's
// own extension for newly-extracted fixture items, yet the layout-test-runner
// requires outputs.ipmt to treat an item as a runnable case — without it a
// freshly-moved case silently drops out of the corpus.
var standardOutputKeys = []string{"ipmt", "json", "layout.json", "ipm.svg", "md"}

func main() {
	check := flag.Bool("check", false, "dry-run: exit 1 if any outputs hash is stale, write nothing")
	verbose := flag.Bool("v", false, "print one line per changed item key (old -> new)")
	flag.Usage = func() {
		fmt.Fprintln(os.Stderr, "Usage: refs-rehash [--check] [-v] [dir ...]")
		fmt.Fprintln(os.Stderr, "Refreshes _refs.json \"outputs\" SHA1 maps from on-disk artifact files.")
		fmt.Fprintf(os.Stderr, "Default dirs: %v\n", defaultDirs)
		fmt.Fprintln(os.Stderr, "\nFlags:")
		cli.PrintDefaults(flag.CommandLine, os.Stderr)
	}
	flag.Parse()

	dirs := flag.Args()
	if len(dirs) == 0 {
		dirs = defaultDirs
	}

	anyStale := false
	for _, dir := range dirs {
		stale, err := rehashDir(dir, *check, *verbose)
		if err != nil {
			fmt.Fprintf(os.Stderr, "refs-rehash: %s: %v\n", dir, err)
			os.Exit(2)
		}
		anyStale = anyStale || stale
	}
	if *check && anyStale {
		os.Exit(1)
	}
}

// rehashDir refreshes dir/_refs.json. Returns whether anything was stale.
func rehashDir(dir string, check, verbose bool) (bool, error) {
	refs, err := filterutil.LoadRefs(dir)
	if err != nil {
		return false, fmt.Errorf("load _refs.json: %w", err)
	}

	changedItems := 0
	for ei := range refs {
		for ii := range refs[ei].Items {
			item := &refs[ei].Items[ii]
			fresh := rehashItem(dir, item.Destination, item.Outputs)
			if outputsEqual(item.Outputs, fresh) {
				continue
			}
			if verbose {
				reportItemDiff(dir, item.Destination, item.Outputs, fresh)
			}
			item.Outputs = fresh
			changedItems++
		}
	}

	refsPath := filepath.Join(dir, "_refs.json")
	if changedItems == 0 {
		fmt.Printf("fresh: %s\n", refsPath)
		return false, nil
	}
	if check {
		fmt.Fprintf(os.Stderr, "STALE: %s (%d items)\n", refsPath, changedItems)
		return true, nil
	}
	if err := writeJSONAtomic(refsPath, refs); err != nil {
		return true, fmt.Errorf("write _refs.json: %w", err)
	}
	fmt.Printf("rehashed: %s (%d items)\n", refsPath, changedItems)
	return true, nil
}

// rehashItem computes the fresh outputs map for one destination stem. The
// candidate key set is the union of already-recorded keys (this preserves the
// snippet's own extension key, e.g. "ipmt") and the standard
// generated suffixes. Missing files drop their key.
func rehashItem(dir, destination string, old map[string]string) map[string]string {
	keys := map[string]struct{}{}
	for k := range old {
		keys[k] = struct{}{}
	}
	for _, k := range standardOutputKeys {
		keys[k] = struct{}{}
	}

	fresh := make(map[string]string, len(keys))
	for k := range keys {
		path := filepath.Join(dir, destination+"."+k)
		if hash, err := computeFileSHA1(path); err == nil {
			fresh[k] = hash
		}
	}
	return fresh
}

func outputsEqual(a, b map[string]string) bool {
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if b[k] != v {
			return false
		}
	}
	return true
}

func reportItemDiff(dir, destination string, old, fresh map[string]string) {
	keys := map[string]struct{}{}
	for k := range old {
		keys[k] = struct{}{}
	}
	for k := range fresh {
		keys[k] = struct{}{}
	}
	sorted := make([]string, 0, len(keys))
	for k := range keys {
		sorted = append(sorted, k)
	}
	sort.Strings(sorted)
	for _, k := range sorted {
		ov, oOK := old[k]
		fv, fOK := fresh[k]
		switch {
		case oOK && !fOK:
			fmt.Printf("  %s/%s.%s: %s -> (file gone, key dropped)\n", dir, destination, k, short(ov))
		case !oOK && fOK:
			fmt.Printf("  %s/%s.%s: (new) -> %s\n", dir, destination, k, short(fv))
		case ov != fv:
			fmt.Printf("  %s/%s.%s: %s -> %s\n", dir, destination, k, short(ov), short(fv))
		}
	}
}

func short(h string) string {
	if len(h) > 12 {
		return h[:12]
	}
	return h
}

func computeFileSHA1(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	h := sha1.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// writeJSONAtomic matches sync-test-cases' formatting (4-space indent,
// trailing newline) so the two tools never fight over the file encoding.
func writeJSONAtomic(path string, v any) error {
	tmp := fmt.Sprintf("%s.tmp.%d.%d", path, os.Getpid(), time.Now().UnixNano())
	f, err := os.OpenFile(tmp, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
	if err != nil {
		return err
	}
	enc := json.NewEncoder(f)
	enc.SetIndent("", "    ")
	if err := enc.Encode(v); err != nil {
		f.Close()
		os.Remove(tmp)
		return err
	}
	if err := f.Close(); err != nil {
		os.Remove(tmp)
		return err
	}
	return os.Rename(tmp, path)
}
